// <auto-generated />
using System;
using Mde.Project.Api.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mde.Project.Api.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Products.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4c2bb7e-4bca-412d-9c10-9d35ffd5cc49"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8564),
                            Name = "Albert Heijn"
                        },
                        new
                        {
                            Id = new Guid("b0989e94-7672-4a91-a1ae-fc04d08504dd"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8568),
                            Name = "LU"
                        },
                        new
                        {
                            Id = new Guid("4554a065-64b4-4bcb-af54-061d5c4b9c9b"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8570),
                            Name = "Purina One"
                        },
                        new
                        {
                            Id = new Guid("d905ae1d-77e0-4de1-b2a5-50f98115b755"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8571),
                            Name = "Van Wijngaarden"
                        },
                        new
                        {
                            Id = new Guid("feeb22d0-55b8-44b7-aca0-a0684d0face9"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8573),
                            Name = "Dreft"
                        },
                        new
                        {
                            Id = new Guid("b9cf81f1-9f8e-4554-a93a-99d236d873dc"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8579),
                            Name = "Pampers"
                        },
                        new
                        {
                            Id = new Guid("548731b0-d59d-4aeb-bd5f-49e4f453a163"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8581),
                            Name = "Axe"
                        },
                        new
                        {
                            Id = new Guid("7591840b-6686-4c4d-9a4f-5c581baae897"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8582),
                            Name = "Dash"
                        },
                        new
                        {
                            Id = new Guid("9b557a9d-6970-48f6-8b45-eec45decc7eb"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8584),
                            Name = "Lea & Perrins"
                        });
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalesPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("SalesTaxId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SalesTaxId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ed190a8-ac31-4acc-bcd3-64d1030b4f80"),
                            Barcode = "0800345750178",
                            BrandId = new Guid("a4c2bb7e-4bca-412d-9c10-9d35ffd5cc49"),
                            CategoryId = new Guid("67a44f61-b799-4fb5-a3d0-8365b8dd1ee6"),
                            CreatedOn = new DateTime(2025, 5, 26, 15, 10, 47, 938, DateTimeKind.Unspecified).AddTicks(2250),
                            Description = "Let op: dit product wordt in de winkel gewogen om de exacte prijs vast te stellen",
                            Image = "103114cc-50b0-40c4-aec5-3621d29b6cfc.jpg",
                            Name = "AH Witlof los (kg)",
                            SalesPrice = 1.17m,
                            SalesTaxId = new Guid("e9014240-e5f9-4248-b870-2e1bf67bf72a")
                        },
                        new
                        {
                            Id = new Guid("91707164-ecd8-4f8f-a1f3-219e70b1ca48"),
                            Barcode = "8856729110016",
                            BrandId = new Guid("a4c2bb7e-4bca-412d-9c10-9d35ffd5cc49"),
                            CategoryId = new Guid("04894e91-b148-4ab3-8948-ab9827f76458"),
                            CreatedOn = new DateTime(2025, 5, 26, 15, 14, 15, 880, DateTimeKind.Unspecified).AddTicks(2693),
                            Description = "De AH Schep & Schoon Super Hygiëne kattenbakvulling is een fijne kattenbakvulling, verrijkt met blue bit korrels waardoor de hardnekkige geurtjes van urine én uitwerpselen worden ingesloten.",
                            Image = "5507ede3-f158-4a90-be22-bb80dd8d0cba.jpg",
                            Name = "AH Kattenbakvulling ex hygiene schep&schoon",
                            SalesPrice = 3.15m,
                            SalesTaxId = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e")
                        },
                        new
                        {
                            Id = new Guid("92899278-1e8c-4cbc-9fe1-9262e446b131"),
                            Barcode = "7934592776551",
                            BrandId = new Guid("4554a065-64b4-4bcb-af54-061d5c4b9c9b"),
                            CategoryId = new Guid("04894e91-b148-4ab3-8948-ab9827f76458"),
                            CreatedOn = new DateTime(2025, 5, 26, 15, 18, 21, 311, DateTimeKind.Unspecified).AddTicks(7540),
                            Description = "Purina one adult kattenvoer rijk aan zalm is speciaal afgestemd op volwassen katten (van 1 jaar en ouder)",
                            Image = "d7903db8-4519-4b46-9dc9-6f6516784699.jpg",
                            Name = "Purina ONE Adult rijk aan zalm",
                            SalesPrice = 4.70m,
                            SalesTaxId = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e")
                        },
                        new
                        {
                            Id = new Guid("363bc808-b527-4204-a27d-d45e04040627"),
                            Barcode = "0784244549357",
                            BrandId = new Guid("a4c2bb7e-4bca-412d-9c10-9d35ffd5cc49"),
                            CategoryId = new Guid("67a44f61-b799-4fb5-a3d0-8365b8dd1ee6"),
                            CreatedOn = new DateTime(2025, 5, 26, 15, 23, 30, 619, DateTimeKind.Unspecified).AddTicks(5150),
                            Description = "De banaan is de bekendste tropische fruitsoort en een echte favoriet. Lekker als tussendoortje of om mee nemen als snack voor onderweg.",
                            Image = "db676fc2-134b-42b3-96bb-c3d27063743e.jpg",
                            Name = "AH Bananen tros",
                            SalesPrice = 0.90m,
                            SalesTaxId = new Guid("e9014240-e5f9-4248-b870-2e1bf67bf72a")
                        },
                        new
                        {
                            Id = new Guid("88062673-cff2-40e7-b378-26065c11ffe0"),
                            Barcode = "3448530513633",
                            BrandId = new Guid("a4c2bb7e-4bca-412d-9c10-9d35ffd5cc49"),
                            CategoryId = new Guid("67a44f61-b799-4fb5-a3d0-8365b8dd1ee6"),
                            CreatedOn = new DateTime(2025, 5, 26, 15, 28, 49, 308, DateTimeKind.Unspecified).AddTicks(5608),
                            Description = "Heerlijk zacht en mals witbrood met een mooie gemelleerde korst.",
                            Image = "900496d5-eed8-4296-93c9-e1af3451af9c.jpg",
                            Name = "AH Extra lang lekker tijger wit heel",
                            SalesPrice = 1.80m,
                            SalesTaxId = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e")
                        },
                        new
                        {
                            Id = new Guid("d21141fa-525a-486e-a372-a10a06d2b311"),
                            Barcode = "0324255992584",
                            BrandId = new Guid("a4c2bb7e-4bca-412d-9c10-9d35ffd5cc49"),
                            CategoryId = new Guid("67a44f61-b799-4fb5-a3d0-8365b8dd1ee6"),
                            CreatedOn = new DateTime(2025, 5, 26, 19, 14, 39, 747, DateTimeKind.Unspecified).AddTicks(3425),
                            Description = "Deze kipburgers zijn al voorgegaard, alleen even bakken in de pan voor een heerlijk knapperig laagje.",
                            Image = "8b125098-ac4d-4caa-8e21-a53283ee481b.jpg",
                            Name = "AH Scharrel kipburger 4 stuks",
                            SalesPrice = 3.75m,
                            SalesTaxId = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e")
                        },
                        new
                        {
                            Id = new Guid("33a825fe-215f-4d56-85ed-24c9478f618b"),
                            Barcode = "4370107769466",
                            BrandId = new Guid("d905ae1d-77e0-4de1-b2a5-50f98115b755"),
                            CategoryId = new Guid("67a44f61-b799-4fb5-a3d0-8365b8dd1ee6"),
                            CreatedOn = new DateTime(2025, 5, 26, 19, 18, 11, 751, DateTimeKind.Unspecified).AddTicks(1596),
                            Description = "De authentieke Zaanse mayonaise in handige knijpfles met steropening.",
                            Image = "576bc590-9fc3-4bc7-8760-71eea0326a7e.jpg",
                            Name = "Van Wijngaarden's Zaanse mayonaise",
                            SalesPrice = 3.15m,
                            SalesTaxId = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e")
                        },
                        new
                        {
                            Id = new Guid("b0f83058-6b6a-442d-a8c9-740bfa96947b"),
                            Barcode = "4844730411660",
                            BrandId = new Guid("9b557a9d-6970-48f6-8b45-eec45decc7eb"),
                            CategoryId = new Guid("67a44f61-b799-4fb5-a3d0-8365b8dd1ee6"),
                            CreatedOn = new DateTime(2025, 5, 26, 19, 19, 54, 785, DateTimeKind.Unspecified).AddTicks(4121),
                            Description = "Lea en perrins worcestershire sauce is een zuur-pittige tafelsaus voor vlees- en visgerechten en is met haar uitgesproken smaak sinds 1837 een van de meest invloedrijke sauzen in de wereldkeuken.",
                            Image = "ea13d884-f19c-4b17-b6f8-d80f5710cb75.jpg",
                            Name = "Lea & Perrins Worcestershire saus",
                            SalesPrice = 1.96m,
                            SalesTaxId = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e")
                        },
                        new
                        {
                            Id = new Guid("291b5c1b-3f92-4ddf-a9ae-aeb0cd973294"),
                            Barcode = "5513225762264",
                            BrandId = new Guid("7591840b-6686-4c4d-9a4f-5c581baae897"),
                            CategoryId = new Guid("e60f3f21-3c5d-4cb6-bde3-577c74f01b70"),
                            CreatedOn = new DateTime(2025, 5, 26, 19, 29, 23, 498, DateTimeKind.Unspecified).AddTicks(5112),
                            Description = "Dash witter dan wit + anti-residu technologie waspoeder biedt briljant schone resultaten, zelfs bij een koud en kort cyclus.",
                            Image = "7a451181-5686-48e7-a8c0-2268ae40ed72.jpg",
                            Name = "Dash Poeder original bel",
                            SalesPrice = 1120.00m,
                            SalesTaxId = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e")
                        },
                        new
                        {
                            Id = new Guid("df8a5743-1f68-4cec-8c7c-202155168029"),
                            Barcode = "5222172458266",
                            BrandId = new Guid("548731b0-d59d-4aeb-bd5f-49e4f453a163"),
                            CategoryId = new Guid("ab76d188-6d72-4560-a6b8-f8e3e1e426e4"),
                            CreatedOn = new DateTime(2025, 5, 26, 19, 51, 43, 950, DateTimeKind.Unspecified).AddTicks(8221),
                            Description = "Axe apollo 3-in-1 douchegel voor lichaam, gezicht en haar hydrateert en houdt je 12 uur lang fris, met de heerlijke geur van salie en cederhout.",
                            Image = "aef8c3f1-a525-4ca2-b4a4-e17e04511a7a.jpg",
                            Name = "Axe Apollo showergel",
                            SalesPrice = 2.50m,
                            SalesTaxId = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e")
                        },
                        new
                        {
                            Id = new Guid("dc9e838a-95f9-4da7-afcb-1f1adf676fda"),
                            Barcode = "1589354243664",
                            BrandId = new Guid("548731b0-d59d-4aeb-bd5f-49e4f453a163"),
                            CategoryId = new Guid("ab76d188-6d72-4560-a6b8-f8e3e1e426e4"),
                            CreatedOn = new DateTime(2025, 5, 26, 19, 52, 54, 39, DateTimeKind.Unspecified).AddTicks(9339),
                            Description = "Axe black deodorant bodyspray: voor effectieve bescherming en een onweerstaanbare geur.",
                            Image = "14d0f9b8-8597-4556-b9bb-cf77b8d00ddc.jpg",
                            Name = "Axe Black deodorant bodyspray",
                            SalesPrice = 3.80m,
                            SalesTaxId = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e")
                        },
                        new
                        {
                            Id = new Guid("5ef148b2-bf95-4dc6-b249-6b2a1e509f8a"),
                            Barcode = "0420170197490",
                            BrandId = new Guid("b9cf81f1-9f8e-4554-a93a-99d236d873dc"),
                            CategoryId = new Guid("55a177b3-626d-46da-bd19-1fbc3f0e09d3"),
                            CreatedOn = new DateTime(2025, 5, 26, 21, 10, 22, 601, DateTimeKind.Unspecified).AddTicks(79),
                            Description = "Pampers n graden1 luiers voor comfort en bescherming van de gevoelige huid.",
                            Image = "e3bbcf0f-0622-407c-8ffa-7f4ae8cfbd06.jpg",
                            Name = "Pampers Premium protection luiers maat 6",
                            SalesPrice = 10.30m,
                            SalesTaxId = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e")
                        },
                        new
                        {
                            Id = new Guid("07ba3b4a-946c-47a4-bb67-beb795db8573"),
                            Barcode = "3609655643166",
                            BrandId = new Guid("a4c2bb7e-4bca-412d-9c10-9d35ffd5cc49"),
                            CategoryId = new Guid("55a177b3-626d-46da-bd19-1fbc3f0e09d3"),
                            CreatedOn = new DateTime(2025, 5, 26, 22, 31, 28, 211, DateTimeKind.Unspecified).AddTicks(4786),
                            Description = "AH Beregoede Baby lotiondoekjes sensitive​.",
                            Image = "54e83a02-3fb3-45f9-a414-154ccef7f110.jpg",
                            Name = "AH Beregoede baby lotiondoekjes sensitive",
                            SalesPrice = 0.62m,
                            SalesTaxId = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e")
                        },
                        new
                        {
                            Id = new Guid("7d9770fa-6902-4359-88de-765a3a8a417c"),
                            Barcode = "9541621865377",
                            BrandId = new Guid("feeb22d0-55b8-44b7-aca0-a0684d0face9"),
                            CategoryId = new Guid("e60f3f21-3c5d-4cb6-bde3-577c74f01b70"),
                            CreatedOn = new DateTime(2025, 5, 26, 22, 38, 52, 664, DateTimeKind.Unspecified).AddTicks(8507),
                            Description = "Dreft platinum quickwash original met vloeibaar afwasmiddel ben je sneller de keuken uit door sneller en moeiteloos schoonmaken.",
                            Image = "96718dcf-3431-428b-9a6d-80fc2e9d5491.jpg",
                            Name = "Dreft Afwasmiddel platinum quick wash original",
                            SalesPrice = 2.37m,
                            SalesTaxId = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e")
                        },
                        new
                        {
                            Id = new Guid("7f74c69a-ff82-4cb9-9476-5cdb4003367b"),
                            Barcode = "4006381333948",
                            BrandId = new Guid("a4c2bb7e-4bca-412d-9c10-9d35ffd5cc49"),
                            CategoryId = new Guid("67a44f61-b799-4fb5-a3d0-8365b8dd1ee6"),
                            CreatedOn = new DateTime(2025, 5, 17, 16, 22, 23, 415, DateTimeKind.Unspecified).AddTicks(7325),
                            Description = "Deze smakelijk gerookte zalmfilet is lekker op de boterham met verse dille en ideaal voor fijne hapjes, op toastjes of blini's met wat zure room.",
                            Image = "1c220f9e-3741-4a9e-a968-7eca9010c4ff.jpg",
                            Name = "AH Gerookte zalm",
                            SalesPrice = 3.60m,
                            SalesTaxId = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e")
                        },
                        new
                        {
                            Id = new Guid("e82fd8cb-d681-4d10-a5f7-5e919e51af31"),
                            Barcode = "4006381333962",
                            BrandId = new Guid("a4c2bb7e-4bca-412d-9c10-9d35ffd5cc49"),
                            CategoryId = new Guid("67a44f61-b799-4fb5-a3d0-8365b8dd1ee6"),
                            CreatedOn = new DateTime(2025, 5, 17, 16, 22, 23, 415, DateTimeKind.Unspecified).AddTicks(7331),
                            Description = "Franse kaas",
                            Image = "78f71df6-f8e4-4407-8132-2e14c818d0cd.jpg",
                            Name = "AH Romige brie 60+",
                            SalesPrice = 1.50m,
                            SalesTaxId = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e")
                        },
                        new
                        {
                            Id = new Guid("fa31206e-5134-4158-8ffa-fe35049330f6"),
                            Barcode = "4006381333931",
                            BrandId = new Guid("b0989e94-7672-4a91-a1ae-fc04d08504dd"),
                            CategoryId = new Guid("67a44f61-b799-4fb5-a3d0-8365b8dd1ee6"),
                            CreatedOn = new DateTime(2025, 5, 17, 16, 22, 23, 415, DateTimeKind.Unspecified).AddTicks(7320),
                            Description = "Dunne, knapperige biscuitstokjes bedekt met heerlijke melkchocolade.",
                            Image = "d17ec364-5dfd-4f5a-96e7-2b0d6bdb7893.jpg",
                            Name = "LU Mikado melk chocolade",
                            SalesPrice = 165.00m,
                            SalesTaxId = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e")
                        });
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Products.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67a44f61-b799-4fb5-a3d0-8365b8dd1ee6"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8588),
                            Name = "Voeding"
                        },
                        new
                        {
                            Id = new Guid("ab76d188-6d72-4560-a6b8-f8e3e1e426e4"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8591),
                            Name = "Verzorging"
                        },
                        new
                        {
                            Id = new Guid("04894e91-b148-4ab3-8948-ab9827f76458"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8592),
                            Name = "Huisdieren"
                        },
                        new
                        {
                            Id = new Guid("e60f3f21-3c5d-4cb6-bde3-577c74f01b70"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8594),
                            Name = "Huishouden"
                        },
                        new
                        {
                            Id = new Guid("55a177b3-626d-46da-bd19-1fbc3f0e09d3"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8596),
                            Name = "Baby en Kind"
                        });
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Products.ProductTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TaxRate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ProductTaxes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("572e39bb-2ca6-4175-8aed-2834fe2cad51"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8502),
                            Name = "0%",
                            TaxRate = 0.0
                        },
                        new
                        {
                            Id = new Guid("e9014240-e5f9-4248-b870-2e1bf67bf72a"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8554),
                            Name = "6%",
                            TaxRate = 0.059999999999999998
                        },
                        new
                        {
                            Id = new Guid("4e217eab-6f38-44ac-aee7-4cd1739ce271"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8557),
                            Name = "12%",
                            TaxRate = 0.12
                        },
                        new
                        {
                            Id = new Guid("b2aa3916-c2b1-4435-94c7-878331cf833e"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8559),
                            Name = "21%",
                            TaxRate = 0.20999999999999999
                        });
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Reports.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ProductId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WarehouseId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Statistics.WarehouseStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalRestock")
                        .HasColumnType("int");

                    b.Property<int>("TotalSales")
                        .HasColumnType("int");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("WarehouseStats");
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "640b537e-af5b-414d-9fd5-304706d7a058",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8fa53cac-0c20-442f-b401-6bf106f3ab0f",
                            Email = "siegfried.derdeyn@howest.be",
                            EmailConfirmed = true,
                            FirstName = "Siegfried",
                            LastName = "Derdeyn",
                            LockoutEnabled = false,
                            NormalizedEmail = "SIEGFRIED.DERDEYN@HOWEST.BE",
                            NormalizedUserName = "SIEGFRIED.DERDEYN@HOWEST.BE",
                            PasswordHash = "AQAAAAIAAYagAAAAECK4oVg5svx+x3Hc0okj+h3AqWSnjL9OQj4eY8HcRvzfKbINRANFXihnq8uwvp8KjQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "29e2f6bb-3658-4953-945e-0a72c950b287",
                            TwoFactorEnabled = false,
                            UserName = "siegfried.derdeyn@howest.be"
                        },
                        new
                        {
                            Id = "8a7214da-7deb-4f03-8ee1-0bc19c9f9204",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0d9df6f9-bb0e-4fbb-8af2-d6c08e57bd53",
                            Email = "glenn.deprey@student.howest.be",
                            EmailConfirmed = true,
                            FirstName = "Glenn",
                            LastName = "Deprey",
                            LockoutEnabled = false,
                            NormalizedEmail = "GLENN.DEPREY@STUDENT.HOWEST.BE",
                            NormalizedUserName = "GLENN.DEPREY@STUDENT.HOWEST.BE",
                            PasswordHash = "AQAAAAIAAYagAAAAEHrnwAo/lMU2e90Pc9szRmbPhtxBzgy5lW5cYWBxWV+L/d0iNijrvFzefdXF+MiKfw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f505a6bb-0226-4926-beaf-fe506832f952",
                            TwoFactorEnabled = false,
                            UserName = "glenn.deprey@student.howest.be"
                        });
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Earnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EditedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("GoogleInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoogleInfoId")
                        .IsUnique()
                        .HasFilter("[GoogleInfoId] IS NOT NULL");

                    b.HasIndex("LocationInfoId")
                        .IsUnique();

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e30fbe65-a787-4226-a9a8-be373574ceec"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8785),
                            Earnings = 10000m,
                            GoogleInfoId = new Guid("e27e6faf-66a0-4cbe-9d7a-7a922c84b1d9"),
                            LocationInfoId = new Guid("e737f309-03ce-46fd-8e23-bffd8dcb8a12"),
                            Name = "AH Veurne",
                            Phone = "058 69 01 00",
                            ShortName = "AHBEWV-V"
                        },
                        new
                        {
                            Id = new Guid("b9d2182c-9bb0-47e0-ad6f-107da4f13bd0"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8789),
                            Earnings = 20000m,
                            GoogleInfoId = new Guid("032e6f09-d956-4a63-9fb0-7707dc11aab2"),
                            LocationInfoId = new Guid("73e22f73-d372-4b0e-b09a-4302c39e13db"),
                            Name = "AH Oostende",
                            Phone = "059 36 95 00",
                            ShortName = "AHBEWV-O"
                        });
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Warehouses.WarehouseGoogleInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleAddressId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WarehouseGoogleInfos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e27e6faf-66a0-4cbe-9d7a-7a922c84b1d9"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoogleAddress = "Albert Heijn Veurne, Koksijdestraat, Veurne, Belgium",
                            GoogleAddressId = "ChIJucK6Jt6X3EcRHP0v6wEBFlo"
                        },
                        new
                        {
                            Id = new Guid("032e6f09-d956-4a63-9fb0-7707dc11aab2"),
                            CreatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoogleAddress = "Albert Heijn Oostende, Torhoutsesteenweg, Ostend, Belgium",
                            GoogleAddressId = "ChIJJakyy0mv3EcRNMCeP-A3ZfA"
                        });
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Warehouses.WarehouseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasAutoRefill")
                        .HasColumnType("bit");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RefillQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("WarehouseItems");
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Warehouses.WarehouseLocationInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WarehouseLocationInfos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e737f309-03ce-46fd-8e23-bffd8dcb8a12"),
                            Address = "123 Main St",
                            City = "City A",
                            Country = "Country A",
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8768),
                            Latitude = 20.0,
                            Longitude = 10.0,
                            PostalCode = "12345",
                            State = "State A"
                        },
                        new
                        {
                            Id = new Guid("73e22f73-d372-4b0e-b09a-4302c39e13db"),
                            Address = "456 Elm St",
                            City = "City B",
                            Country = "Country B",
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8771),
                            Latitude = 40.0,
                            Longitude = 30.0,
                            PostalCode = "67890",
                            State = "State B"
                        });
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Warehouses.WarehousePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EditedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GoogleInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhotoUri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoogleInfoId");

                    b.ToTable("WarehousePhotos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("065487d7-2efb-43f0-a6b8-49420cc9b4d3"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8793),
                            GoogleInfoId = new Guid("e27e6faf-66a0-4cbe-9d7a-7a922c84b1d9"),
                            PhotoUri = "https://lh3.googleusercontent.com/place-photos/AJnk2cyV0QKUpAYpc0r7nhWvVWXQjhTklkG-tqr7-cCV0hqw752hTcDFio7v1TS7pieay3dGJyZKE1qcSsYYz2Nc1Ia4MqrzOzCL8yHLJqWcuP0tN1DVvl5OgdNROhD251l2wc6D4J76CDRYqF-9=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("0a5ce818-6b46-4634-b959-0ef2200ef068"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8796),
                            GoogleInfoId = new Guid("e27e6faf-66a0-4cbe-9d7a-7a922c84b1d9"),
                            PhotoUri = "https://lh3.googleusercontent.com/places/ANXAkqFCZz1f5-dL1L3OwpxGrN9BEeYjWba3xb455XIBgW-QpzakxwSeJYon89dJGX_MpRtj5p8LKLpvYkmOH-0fiD8F_OzWOax35zw=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("2db8d636-ecd1-4827-b477-3570be73ae63"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8799),
                            GoogleInfoId = new Guid("e27e6faf-66a0-4cbe-9d7a-7a922c84b1d9"),
                            PhotoUri = "https://lh3.googleusercontent.com/places/ANXAkqFUatKQMvNT7Um3L6mrHJh_hJ_AVciMztLc_sCwoyLACEx0Z0DyOjY_pBlwX03fiuPqo98dLpnmpOJDX7rjnmUm9nOp8U7nFqw=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("9677d799-c4be-4f39-8951-586f458ace74"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8800),
                            GoogleInfoId = new Guid("e27e6faf-66a0-4cbe-9d7a-7a922c84b1d9"),
                            PhotoUri = "https://lh3.googleusercontent.com/places/ANXAkqF73sx2p_xjCyaSEh-nsT-pYbG0tbuiiW7Iiq680aT7cI4SWiji9zmDVbM6IdT0I66Mn2ILIgaRUT-vHelRV1-QUiQswPYbIAY=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("8dacf0ed-8419-417e-86b1-bf0b98fabadc"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8802),
                            GoogleInfoId = new Guid("e27e6faf-66a0-4cbe-9d7a-7a922c84b1d9"),
                            PhotoUri = "https://lh3.googleusercontent.com/place-photos/AJnk2cwwQ8ZGAyA3PKUTbPqaXvjBlB0R428Cq1xTCwumhZZlPmbptdHabWJOrD_lwhvFTb6ZtuiVXRz4t_T2Qoc_5jAZHXsJdE4S_sqZO1B9mBem8H5D-euptffcEU7PVAc0-6iC6PAG-2TRX8H9oQ=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("80bb7641-d480-44d1-bd3a-13ed9b529722"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8805),
                            GoogleInfoId = new Guid("e27e6faf-66a0-4cbe-9d7a-7a922c84b1d9"),
                            PhotoUri = "https://lh3.googleusercontent.com/places/ANXAkqH9tKAG77TzGH2pnwZGJLexdPLLYViha-i3LBWX9-8vhnJRqu2IQfMyRK7dvB3J9kzdc2RyhsmASDhs2YfbIyPczCuzDeEHAcU=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("8a571e5e-96bc-4c25-bf6a-9660ae315d11"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8807),
                            GoogleInfoId = new Guid("e27e6faf-66a0-4cbe-9d7a-7a922c84b1d9"),
                            PhotoUri = "https://lh3.googleusercontent.com/place-photos/AJnk2cyvHuVkb0HN2eVbSYFjJ0Unv-ke4JKVCyqDFvnTZcr1eBdRTbvRZLrnMUOgQ3Ad-wZxQE8bznEWhIzNMsPCj_FGRYxhMxOxZGBDMJmtC-nxGhpMPKL0XQmySiH0tSCPETOCy6eaHF0mYmyaEQ=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("6b3f6e47-e4a8-4c2e-85b9-4c9b999c94e3"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8832),
                            GoogleInfoId = new Guid("e27e6faf-66a0-4cbe-9d7a-7a922c84b1d9"),
                            PhotoUri = "https://lh3.googleusercontent.com/places/ANXAkqEAjmvnI1AiffFG-FOjtcVTZ7wq1GUEPh_1q_KGk8IWVIisol62un2y-RqEEteNQLP5-jx1uLpCBWeDZIyISStK4eOTkvQrZ2Y=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("85a3c8c3-7e99-4089-93f8-4a035a7aac41"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8835),
                            GoogleInfoId = new Guid("e27e6faf-66a0-4cbe-9d7a-7a922c84b1d9"),
                            PhotoUri = "https://lh3.googleusercontent.com/places/ANXAkqEtayDJrKMJzeuJhaBlX67L0vrSBSEi7atRtbX0fF7mptHrQmAoH12YjPai_iRmdFpaIut8MicT8YVmP4Pxkwn0L5HGro5xhLE=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("8c4b608c-291d-4de1-b018-9dddb603800a"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8838),
                            GoogleInfoId = new Guid("e27e6faf-66a0-4cbe-9d7a-7a922c84b1d9"),
                            PhotoUri = "https://lh3.googleusercontent.com/places/ANXAkqHD6KsHJ92smoCMkCpvMg66IoEz4tfXsbeWXeHSNXfv_F9YZbM6gm0KQIvGDoEo3g5P_fnJbhK6O2QMP4n4vZuk4Nh_04Ybji8=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("0fd1f091-505d-47f9-87c0-0905819f0e9a"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8841),
                            GoogleInfoId = new Guid("032e6f09-d956-4a63-9fb0-7707dc11aab2"),
                            PhotoUri = "https://lh3.googleusercontent.com/place-photos/AJnk2cx3V5M_RQj8F_Y2WhJ5qg2iLQUibOtC7izUEDVCQ_RD_KFBDop1UANboEM6o21yO7U2RuennHqHomMrBtZkpUm11uGEfmY78WKRTCrzzhyeIAUv7lBPidREKw8WuRWTl3DchP3wkdJmIaVH=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("917d4b2c-42aa-48b3-9fe4-41de02569cb8"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8843),
                            GoogleInfoId = new Guid("032e6f09-d956-4a63-9fb0-7707dc11aab2"),
                            PhotoUri = "https://lh3.googleusercontent.com/place-photos/AJnk2cwF-HFGQc4GQkQgXZReh13PWDIJEAR5_FEVfOAKScyZVggjnw7EEX8F_k0s09xlcUjv2pLioT58D47ivYLgxoqHtZ79lpMdBYj4QJ8MoDzYyByD20e6E2ayNtNPpPs384vTzyW6hX9dLEN6VA=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("33279093-cee9-4618-bd46-85cb261a6a0d"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8845),
                            GoogleInfoId = new Guid("032e6f09-d956-4a63-9fb0-7707dc11aab2"),
                            PhotoUri = "https://lh3.googleusercontent.com/place-photos/AJnk2cxKWGXcUmrl1UuBfU5N_1Ib4Awzo1BjRqo3ZywWKARTpIKvcITTwRIGpUEObruZKYONGbkuitp-bBO3LcyU6v5x2XV62GAHYlilwweOEZHdW4UnOBOxdVzn__VaNwWLqkWbEpI2fsEk0LQvEg=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("2d8b5178-b830-4a4a-bcb0-852cebd31f84"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8846),
                            GoogleInfoId = new Guid("032e6f09-d956-4a63-9fb0-7707dc11aab2"),
                            PhotoUri = "https://lh3.googleusercontent.com/place-photos/AJnk2cwZZW_MIP10MKKSKTKkuImanBos4E3TRBmJi9ySugTwK749k29MaG9V3GpAy6GoedfuLhiYt2jo5tQyG_6N12A1ILXq7bP4RhIc0kQM5Ld23AX-_7pueZ3C0_oMqXVZzwJhY1-PwmGh-o7N=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("c1e30422-c64e-4065-900d-baa6707e35eb"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8848),
                            GoogleInfoId = new Guid("032e6f09-d956-4a63-9fb0-7707dc11aab2"),
                            PhotoUri = "https://lh3.googleusercontent.com/place-photos/AJnk2cyWqxh6Oi6pNdXrsy6WmwfqXGHPuge_3unkJF2q9XB5YqLrZr7K2d1vvFGXiQB6rPOIRBb5UMJUP0pmhzJURmIrpJYJzBf5aAeGvtPlXrUNIGI6tkpuTceoLcnbbL3GhgBSlXDG9g8VbFcT75A=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("61621208-0f39-4ed7-b46c-6b0eee0f67ea"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8850),
                            GoogleInfoId = new Guid("032e6f09-d956-4a63-9fb0-7707dc11aab2"),
                            PhotoUri = "https://lh3.googleusercontent.com/place-photos/AJnk2cxCRY7Nu1k6geIqE6Ow9Q8A17AigUNkP_anyn0ejNkUC9SzBiePj6FcxSVXdoHawdsRkPYaXb74UFmzDNF19_kfr9mryCf0eszGtRu41vzoyi-y-TK0EqbohrQDVh0otStjpAZTELtnoKffyw=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("da9ed8f6-4e24-4111-a8ce-1b81ca8d4d66"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8853),
                            GoogleInfoId = new Guid("032e6f09-d956-4a63-9fb0-7707dc11aab2"),
                            PhotoUri = "https://lh3.googleusercontent.com/place-photos/AJnk2cx0xcKTzbbxdSkmztmotc3niWWoDgzMxHpNxvlzYRINKB8Ala0JpVxeq8SnqSfoHVhqsEwaPT5mmhBEYrPgssqlYRmR6JtWbuQdq-O-RTkbM348rk2D8pCJM1HRZPwmPPyd0Cc0jaBWs5MVCQ=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("96cb5905-d28d-4d87-a493-9afa637653d9"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8855),
                            GoogleInfoId = new Guid("032e6f09-d956-4a63-9fb0-7707dc11aab2"),
                            PhotoUri = "https://lh3.googleusercontent.com/place-photos/AJnk2cwfwWkMEzaisUP5A9UBXYMHT3fMyJQ_rDuN7E6czy38Bkqqi_nmU2t6Jarb2Lo4iCWCMH881ERLjv7CbzczOQDNrd5SgLHrqBlBzlXAzSJH2ima1ek-rySZgZtV2eg214phQZEAxl-4m0x7FkE=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("fcda3b9e-ce8f-49b3-ba2f-835bc7f9ed34"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8857),
                            GoogleInfoId = new Guid("032e6f09-d956-4a63-9fb0-7707dc11aab2"),
                            PhotoUri = "https://lh3.googleusercontent.com/place-photos/AJnk2czTVkjR_fVLL61EAHEn2RpkhTlInggcqsmTyo-89e-N2_3z3rxdpvOmCJ96_krO04pBLnJ-VbSbHnM5u4U6gl7C7YePKP55hSDfxYel8pIWVkkRZsQ7uXo73_GIYqPAP9UGbq77s-F4linufOs=s4800-w120-h120"
                        },
                        new
                        {
                            Id = new Guid("2fdefac0-8852-4eb1-81b2-e37594df24f7"),
                            CreatedOn = new DateTime(2025, 5, 28, 12, 25, 48, 818, DateTimeKind.Local).AddTicks(8859),
                            GoogleInfoId = new Guid("032e6f09-d956-4a63-9fb0-7707dc11aab2"),
                            PhotoUri = "https://lh3.googleusercontent.com/place-photos/AJnk2cxBfrBIA5vR8QuuLat6hruRnyKQmTeURCWCs32dskSGCKx-XypFJ-cPUZB-vmmzhRrS66IKu49Zfs0wVsUIF8MtQ70_XYK60DR7zU9rJwT17TaiwRL6AKamn9VY520fCkQwzGfT2wlGO5A4EA=s4800-w120-h120"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "6ff26741-5e4a-4378-b03e-0987c53103b8",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "561cfac6-9a45-4d69-844a-1d50dd115b8c",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "640b537e-af5b-414d-9fd5-304706d7a058",
                            RoleId = "6ff26741-5e4a-4378-b03e-0987c53103b8"
                        },
                        new
                        {
                            UserId = "8a7214da-7deb-4f03-8ee1-0bc19c9f9204",
                            RoleId = "561cfac6-9a45-4d69-844a-1d50dd115b8c"
                        },
                        new
                        {
                            UserId = "8a7214da-7deb-4f03-8ee1-0bc19c9f9204",
                            RoleId = "6ff26741-5e4a-4378-b03e-0987c53103b8"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Products.Product", b =>
                {
                    b.HasOne("Mde.Project.Api.Core.Entities.Products.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mde.Project.Api.Core.Entities.Products.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mde.Project.Api.Core.Entities.Products.ProductTax", "SalesTax")
                        .WithMany()
                        .HasForeignKey("SalesTaxId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("SalesTax");
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Reports.Report", b =>
                {
                    b.HasOne("Mde.Project.Api.Core.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mde.Project.Api.Core.Entities.Warehouses.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Statistics.WarehouseStats", b =>
                {
                    b.HasOne("Mde.Project.Api.Core.Entities.Warehouses.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Warehouses.Warehouse", b =>
                {
                    b.HasOne("Mde.Project.Api.Core.Entities.Warehouses.WarehouseGoogleInfo", "GoogleInfo")
                        .WithOne()
                        .HasForeignKey("Mde.Project.Api.Core.Entities.Warehouses.Warehouse", "GoogleInfoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mde.Project.Api.Core.Entities.Warehouses.WarehouseLocationInfo", "LocationInfo")
                        .WithOne()
                        .HasForeignKey("Mde.Project.Api.Core.Entities.Warehouses.Warehouse", "LocationInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoogleInfo");

                    b.Navigation("LocationInfo");
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Warehouses.WarehouseItem", b =>
                {
                    b.HasOne("Mde.Project.Api.Core.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mde.Project.Api.Core.Entities.Warehouses.Warehouse", "Warehouse")
                        .WithMany("WarehouseItems")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Warehouses.WarehousePhoto", b =>
                {
                    b.HasOne("Mde.Project.Api.Core.Entities.Warehouses.WarehouseGoogleInfo", null)
                        .WithMany("GooglePhotoUris")
                        .HasForeignKey("GoogleInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Mde.Project.Api.Core.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Mde.Project.Api.Core.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mde.Project.Api.Core.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Mde.Project.Api.Core.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Products.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Products.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Warehouses.Warehouse", b =>
                {
                    b.Navigation("WarehouseItems");
                });

            modelBuilder.Entity("Mde.Project.Api.Core.Entities.Warehouses.WarehouseGoogleInfo", b =>
                {
                    b.Navigation("GooglePhotoUris");
                });
#pragma warning restore 612, 618
        }
    }
}
